modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/JsMacrosCE/JsMacros/issues"
license = "MPL-2.0"

[[mixins]]
config="jsmacrosce-common.mixins.json"

[[mixins]]
config="jsmacrosce-neoforge.mixins.json"

[[mods]]
modId = "jsmacrosce"
version = "${version}"
displayName = "JS Macros Community Edition"
authors = "East_Arctica, Wagyourtail"
description = '''
    Javascript Macros for NeoForge
'''

[[dependencies.jsmacrosce]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"
